sonar.projectKey=sentiment-ai
sonar.projectName=SentimentAI
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

# Rapport de couverture généré par pytest-cov
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,.venv/**
sonar.test.exclusions=**/__pycache__/**

# Seuils qualité (Quality Gate)
sonar.qualitygate.wait=true
